global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus selbst
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Keiko API Contracts Service
  - job_name: 'keiko-api-contracts'
    static_configs:
      - targets: ['keiko-api-contracts:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Docker Container Metrics (falls cAdvisor läuft)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
